constellations  = {'Андромеда': "andromeda", 'Близнята': "gemini", 'Близнюки': "gemini",
                   'Велика Ведмедиця': "ursa_major", 'Мала Ведмедиця': "ursa_minor",
                   'Великий Віз': "ursa_major", 'Малий Віз': "ursa_minor",
                   'Великий Пес': "canis_major", 'Терези': "libra", 'Водолій': "aquarius",
                   'Візничий': "auriga", 'Вовк': "lupus", 'Волопас': "bootes",'Волосся Вероніки': "coma_berenices",
                   'Ворон': "corvus", 'Геркулес': "hercules", 'Гідра': "hydra", 'Голуб': "columba",
                   'Гончі Пси': "canes", 'Діва': "virgo", 'Дельфін': "delphinus", 'Дракон': "draco",
                   'Єдиноріг': "monoceros", 'Жертовник': "ara", 'Живописець': "pictor", 'Жирафа': "camelopardalis",
                   'Журавель': "grus", 'Заєць': "lepus", 'Змієносець': "ophiuchus", 'Змія': "serpens",
                   'Золота Риба': "dorado", 'Індіанець': "indus", 'Кассіопея': "cassiopeia", 'Кіль': "carina",
                   'Кит': "cetus", 'Козоріг': "capricornus", 'Компас': "pyxis", 'Корма': "puppis",
                   'Лебідь': "cygnus", 'Лев': "leo", 'Летюча Риба': "volans", 'Ліра': "lyra",
                   'Лисичка': "vulpecula", 'Малий Кінь': "equuleus", 'Малий Лев': "leo_minor",
                   'Малий Пес': "canis_minor", 'Мікроскоп': "microscopium", 'Муха': "musca", 'Насос': "antlia",
                   'Косинець': "norma", 'Орел': "aquila", 'Овен': "aries", 'Октант': "octans", 'Оріон': "orion",
                   'Павич': "pavo", 'Вітрила': "vela", 'Пегас': "pegasus", 'Персей': "perseus",
                   'Піч': "fornax", 'Райський Птах': "apus", 'Рак': "cancer", 'Різець': "caelum", 'Риби': "pisces",
                   'Рись': "lynx", 'Північна Корона': "corona_borealis", 'Секстант': "sextans",
                   'Сітка': "reticulum", 'Скорпіон': "scorpius", 'Скульптор': "sculptor", 'Столова Гора': "mensa",
                   'Стріла': "sagitta", 'Стрілець': "sagittarius", 'Телескоп': "telescopium", 'Телець': "taurus",
                   'Трикутник': "triangulum", 'Тукан': "tucana", 'Фенікс': "phoenix", 'Хамелеон': "chamaeleon",
                   'Центавр': "centaurus", 'Цефей': "cepheus", 'Циркуль': "circinus", 'Годинник': "horologium",
                   'Чаша': "crater", 'Щит': "scutum", 'Ерідан': "eridanus", 'Південна Гідра': "hydrus",
                   'Південна Корона': "corona_australis", 'Південна Риба': "piscis_austrinus",
                   'Південний Хрест': "crux", 'Південний Трикутник': "triangulum_australe", 'Ящірка': "lacerta"}

north_hemisphere = ['Андромеда', 'Близнюки', 'Близнята', 'Велика Ведмедиця', 'Великий Віз', 'Візничий',
                    'Волопас', 'Волосся Вероніки', 'Геркулес', 'Кассіопея', 'Гончі Пси', 'Дельфін', 'Змія',
                    'Дракон', 'Жирафа', 'Лебідь', 'Ліра', 'Лисичка', 'Мала Ведмедиця', 'Малий Лев', 'Овен',
                    'Персей', 'Рак', 'Рись', 'Північна Корона', 'Стріла', 'Цефей', 'Телець', 'Трикутник', 'Ящірка']
